inherit_gem:
  syntax_tree: config/rubocop.yml

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

Layout/LineLength:
  Max: 120
  AutoCorrect: true

Style/StringLiterals:
  EnforcedStyle: single_quotes

Metrics/ModuleLength:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Enabled: false

Documentation:
  Enabled: false
