AllCops:
  TargetRubyVersion: 3.1

Layout/LineLength:
  Max: 120
  AutoCorrect: true

Metrics/ModuleLength:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Enabled: false

Documentation:
  Enabled: false
