inherit_from:
  - node_modules/@prettier/plugin-ruby/rubocop.yml

AllCops:
  TargetRubyVersion: 3.2

Layout/LineLength:
  Max: 120

Metrics/ModuleLength:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Documentation:
  Enabled: false
